[graph]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "downstream dependency of accesskit_windows with no upgrade path" },
]

[licenses]
version = 2
allow = [
  "Apache-2.0",                     # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
  "Apache-2.0 WITH LLVM-exception", # https://spdx.org/licenses/LLVM-exception.html
  "BSD-2-Clause",                   # https://tldrlegal.com/license/bsd-2-clause-license-(freebsd)
  "BSD-3-Clause",                   # https://tldrlegal.com/license/bsd-3-clause-license-(revised)
  "BSL-1.0",                        # https://tldrlegal.com/license/boost-software-license-1.0-explained
  "CC0-1.0",                        # https://creativecommons.org/publicdomain/zero/1.0/
  "CDLA-Permissive-2.0",            # https://cdla.dev/permissive-2-0/. Used by webpki-roots on Linux.
  "ISC",                            # https://www.tldrlegal.com/license/isc-license
  "MIT",                            # https://tldrlegal.com/license/mit-license
  "MPL-2.0",                        # https://www.mozilla.org/en-US/MPL/2.0/FAQ/ - see Q11.
  "OFL-1.1",                        # https://spdx.org/licenses/OFL-1.1.html
  "Ubuntu-font-1.0",                # https://ubuntu.com/legal/font-licence
  "Unicode-3.0",                    # https://spdx.org/licenses/Unicode-3.0.html
  "Zlib",                           # https://tldrlegal.com/license/zlib-libpng-license-(zlib)
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Pending https://github.com/EmbarkStudios/puffin/pull/234
allow-git = ["https://github.com/tedsteen/puffin.git"]

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
